server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.77.191:3306/mango?serverTimezone=GMT%2B8&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Wjy@018080
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.mango.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.mango.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 80
    height: 80
  tracker-list[0]: 192.168.1.70:22122